// src/components/FilterField/index.tsx
import React, { ReactNode } from 'react'

export enum FilterTypes {
  media = 'media',
  images = 'images',
  vine = 'vine',
  native_video = 'native_video',
  periscope = 'periscope',
  news = 'news',
  links = 'links',
  safe = 'safe',
  verified = 'verified',
  retweets = 'retweets',
  nativeretweets = 'nativeretweets'
}
export type FieldStateType = 'inactive' | 'filterFor' | 'filterOut'
interface MyProps {
  /** Label for filter
   * @default ''
   * */
  label?: string
  /** State of the inputfield */
  fieldState: FieldStateType
  /** The valid boolean filter types from Twitter */
  filterType: FilterTypes
  /** I will pass you the next state which you can set to fieldState */
  onChange?: (value: FieldStateType) => void
  children?: ReactNode
}

const StateMachine = {
  inactive: 'filterFor',
  filterFor: 'filterOut',
  filterOut: 'inactive'
}

/**
 * Filter field
 */
export default function FilterField(props: MyProps) {
  const { fieldState, filterType, label = '', onChange = () => { }, children } = props
  const fieldStateColor: string = {
    inactive: 'grey',
    filterFor: 'lightgreen',
    filterOut: 'red'
  }[fieldState]
  const emoji: string = {
    inactive: '☐',
    filterFor: '✓',
    filterOut: '✖'
  }[fieldState]

  const onClick = () => onChange(StateMachine[fieldState] as FieldStateType)
  return (
    // the filter state color is applied to the border and the color of these filters
    <div className="filter-field" onClick={onClick}>
      {label}
      <span className="filter-emoji">{emoji}</span>
      <span>{filterType}</span>
      {children}
    </div>
  )
}

// src/components/FilterField.svelte
<script>
  import { settings } from 'store';
  // export let invalidWarning;
  // export let fieldState;
  // export let fieldName;
  export let fieldType;
  // export let label = '';
  // export let placeholder;
  // export let value;
  // export let onChange;
  // $: {
  //   onChange(value);
  // }
  let fieldState = 'inactive';
  const StateMachine = {
    inactive: 'filterFor',
    filterFor: 'filterOut',
    filterOut: 'inactive'
  };
  // const fieldStateColor = {
  //   inactive: 'grey',
  //   filterFor: 'lightgreen',
  //   filterOut: 'red'
  // }[fieldState];
  $: emoji = {
    inactive: '☐',
    filterFor: '✓',
    filterOut: '✖'
  }[fieldState];

  const onClick = () => {
    fieldState = StateMachine[fieldState];
    settings.update((x) => {
      x.filters[fieldType] = fieldState === 'inactive' ? undefined : fieldState;
      return x;
    });
  };
</script>

<div class="filter-field" on:click="{onClick}">
  <!-- {label} -->
  <span class="filter-emoji">{emoji}</span>
  <span>{fieldType}</span>
  <slot></slot>
</div>
