// src/components/NumberField/index.tsx
import React, { ReactNode } from 'react';
import { useInput } from '@swyx/hooks';

interface MyProps {
  /** label
   * @default ''
   * */
  label?: string;
  onChange?: Function;
  children?: ReactNode;
  fieldName: string;
}

/**
 * number field - has an annoying focus bug in docz : https://codesandbox.io/s/00540zwknn
 */
export default function NumberField(props: MyProps) {
  const { onChange: _onChange, label = '', children, fieldName } = props;
  const { value, onChange, setValue } = useInput('0', _onChange);

  return (
    // has value -> green otherwise grey
    <>
      <label labelfor={fieldName}>{label}</label>
      <input id={fieldName} min="0" type="number" {...{ value, onChange }} />
      <div className="form-control-extras">
        <button onClick={() => setValue('0')}> Reset </button>
        {children}
      </div>
    </>
  );
}

// src/components/NumberField.svelte
<script>
  import { settings } from 'store';
  // export let invalidWarning;
  export let fieldName;
  export let label = '';
  export let placeholder;
  export let value;
  // export let onChange;
  if (!fieldName) throw new Error('must supply fieldName to TextField');
  $: {
    settings.update((x) => {
      x[fieldName] = value;
      return x;
    });
  }
  settings.subscribe((x) => (value = x[fieldName]));
</script>

<div>
  <label labelfor="{fieldName}">{label}</label>
  <input min="0" type="number" id="{fieldName}" bind:value {placeholder} />
  <div class="form-control-extras">
    <button on:click={()=> value=undefined}> Reset </button>
    <slot> </slot>
  </div>
</div>
