// src/components/TextField.svelte
<script>
  import { settings } from 'store';
  // export let invalidWarning;
  export let fieldName;
  export let label = '';
  export let placeholder;
  export let value;
  // export let onChange;
  if (!fieldName) throw new Error('must supply fieldName to TextField');
  $: {
    settings.update((x) => {
      x[fieldName] = value;
      return x;
    });
  }
  settings.subscribe((x) => (value = x[fieldName]));
</script>

<div>
  <!-- {invalidWarning} -->
  <label labelfor="{fieldName}">{label}</label>
  <input id="{fieldName}" bind:value {placeholder} />
  <div class="form-control-extras">
    <slot> </slot>
  </div>
</div>

// src/components/TextField/index.tsx
import React, { ReactNode } from 'react';

interface MyProps {
  /** label of the input
   * @default ''
   * */
  label?: string;
  inputSize?: 'expand';
  fieldName?: string;
  placeholder?: string;
  value: string;
  onChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
  invalidWarning?: string | JSX.Element;
  children?: ReactNode;
}

/**
 * Filter field
 */
export default function TextField(props: MyProps) {
  const {
    fieldName,
    label = '',
    placeholder,
    value,
    onChange,
    invalidWarning,
    children,
    inputSize = '',
  } = props;

  return (
    <>
      {invalidWarning}
      {/** 
        * this label is red when it is invalid and blue when is valid 
        * and isInvalid={!!invalidWarning}
        */}
      {
        label && <label labelfor={fieldName}>
          {label}
        </label>
      }
      <input className={inputSize} id={fieldName} value={value} onChange={onChange} placeholder={placeholder} />
      <div className="form-control-extras">{children}</div>
    </>
  );
}
