// src/App.tsx
import React, { useState } from 'react'
import styled from 'styled-components'
import { useInput } from '@swyx/hooks'
import './patch'
// import { useLoading } from '@swyx/hooks';
import TextField from 'components/TextField'
import NumberField from 'components/NumberField'
import FilterField, { FilterTypes, FieldStateType } from 'components/FilterField'
import Toggle from './Toggle'
function useFilter(type: FilterTypes) {
  const [FilterState, setFilterState] = useState<FieldStateType>('inactive')
  const component = <FilterField key={type} onChange={setFilterState} filterType={type} fieldState={FilterState} />
  return { FilterState, type, component }
}

// /**
//  * convert an array of (non nested) objects to an object of arrays.
//  * assumes all objects are the same shape
//  * */
// type IndexObject = { [index: string]: any } // hacky. :(
// function pivot<T>(arr: (T & IndexObject)[]) {
//   type Subset = { [K in keyof T]?: T[K] }
//   let ans: IndexObject & Subset = {}
//   Object.keys(arr[0]).forEach(k => {
//     ans[k] = arr.map(obj => obj[k])
//   })
//   return ans as { [K in keyof T]: T[K] }
// }
function App({ className }: { className: string }) {
  const [seeFollow, setseeFollow] = useState(true)
  const [minRTs, setminRTs] = useState(0)
  const [minLikes, setminLikes] = useState(0)
  const { ...search } = useInput('')
  const { ...userFrom } = useInput('', () => seeFollow && setseeFollow(false))
  const { ...userTo } = useInput('')
  const { ...datesSince } = useInput('')
  const { ...datesUntil } = useInput('')

  const filters = Object.keys(FilterTypes).map(v => useFilter(v as FilterTypes))

  const submit = () =>
    window.open(
      linkComposer(
        {
          from: userFrom,
          to: userTo,
          search: search,
          since: datesSince,
          until: datesUntil
        },
        filters,
        seeFollow,
        minLikes,
        minRTs
      )
    )

  const today = new Date()
  let yrago = new Date()
  yrago = new Date(yrago.setMonth(yrago.getMonth() - 12)) // subtract 1yr
  let mthago = new Date()
  mthago = new Date(mthago.setMonth(mthago.getMonth() - 1)) // subtract 1mth;
  let mthago3 = new Date()
  mthago3 = new Date(mthago3.setMonth(mthago3.getMonth() - 3)) // subtract 3mth;

  const handleDate = (dateField: { setValue: Function }, newDate: Date) => () =>
    dateField.setValue(newDate.toISOString().slice(0, 10))

  return (
    <div className={className}>
      <main>
        <h1> Better Twitter Search </h1>
        <div style={{ display: 'flex' }}>
          <Toggle isOn={seeFollow} onClick={v => void userFrom.resetValue() || setseeFollow(v)}>
            People You Follow
          </Toggle>
          <TextField {...userFrom} label="User" fieldName="from" />
        </div>
        <TextField {...userTo} label="User" fieldName="to" />
        <TextField {...datesSince} fieldName="Since" placeholder="YYYY-MM-DD">
          <button onClick={handleDate(datesSince, today)}>Today </button>
          <button onClick={handleDate(datesSince, mthago)}>1m </button>
          <button onClick={handleDate(datesSince, mthago3)}>3m</button>
          ago
        </TextField>

        <TextField
          invalidWarning={
            datesSince.value && datesUntil.value && datesSince.value > datesUntil.value ? (
              <div>
                <pre>Since</pre>
                should come before
                <pre>Until</pre>
              </div>
            ) : (
              undefined
            )
          }
          {...datesUntil}
          fieldName="Until"
          placeholder="YYYY-MM-DD"
        >
          <button onClick={handleDate(datesUntil, today)}>Today</button>
          <button onClick={handleDate(datesUntil, mthago)}>1m</button>
          <button onClick={handleDate(datesUntil, mthago3)}>3m</button>
          ago
        </TextField>
        <div id="filters">
          <details>
            <summary>
              <strong>Filters</strong>
            </summary>
            {filters.map(x => x.component)}
          </details>
        </div>
        <div id="quality">
          <details>
            <summary>
              <strong>Quality</strong>
            </summary>
            <NumberField label="min_retweets" onChange={setminRTs} />
            <NumberField label="min_faves" onChange={setminLikes} />
          </details>
        </div>

        <div id="highlight">
          <h3>Search Text </h3>
          <em>leaving blank is ok</em>
          <TextField {...search} placeholder={'search...'} />

          <button type="submit" onClick={submit}>
            Open search results
          </button>
          <p>
            <em>Tips:</em>
          </p>
          <ul>
            <li>Dont forget you can search "exact quotes", @usernames or #hashtags</li>
            <li>Minus Operator e.g. `-RT` or `beer -root`</li>
            <li>OR Operator e.g. `#Emmys OR #Emmys2015`</li>
          </ul>
        </div>

        <div>
          <pre>This app is definitely a work in progress. </pre>
          <pre>
            <a href="https://github.com/sw-yx/bettertwitter">Send ideas/Check out the todo/wishlist here.</a>
          </pre>
          Bouquets and brickbats to <a href="https://twitter.com/swyx">@swyx</a>
        </div>
      </main>
    </div>
  )
}

interface IDictionary<TValue> {
  [id: string]: TValue
}
function linkComposer(
  obj: IDictionary<{ value: string }>,
  filters: {
    FilterState: FieldStateType
    type: FilterTypes
    component: JSX.Element
  }[],
  seeFollow: boolean,
  minLikes: number,
  minRTs: number
) {
  let final = ''
  Object.keys(obj).map(k => {
    if (k === 'search') {
      // special
      final = final.concat(obj[k].value).concat(' ')
    } else if (obj[k].value) {
      final = final.concat(`${k}:${obj[k].value} `)
    }
  })
  filters.forEach(filter => {
    if (filter.FilterState == 'filterFor') final = final.concat(`filter:${filter.type} `)
    if (filter.FilterState == 'filterOut') final = final.concat(`!filter:${filter.type} `)
  })
  if (seeFollow) final = final.concat(`filter:follows `)
  if (minLikes > 0) final = final.concat(`min_faves:${minLikes} `)
  if (minRTs > 0) final = final.concat(`min_retweets:${minRTs} `)
  console.log({ final, seeFollow })
  return `https://mobile.twitter.com/search?src=typd&f=live&q=${encodeURIComponent(final)}`
}

export default styled(App)`
  min-height: 100vh;
  display: grid;
  align-items: center;
  justify-content: center;

  main {
    max-width: 500px;
    width: 90vw;
    display: grid;
  }

  #highlight {
    border: 1px solid red;
    padding: 10px;
    margin-bottom: 10px;

    input {
      font-size: 1.5rem;
    }
    button {
      background-color: lightgreen;
      padding: 10px;
      border: 3px solid black;
      border-radius: 5px;
    }
  }

  #quality {
    margin-bottom: 10px;
  }
`

// src/App.svelte
<script>
  import { get } from 'svelte/store';
  import { settings, tweetURL } from 'store';
  import FilterField from './components/FilterField.svelte';
  import NumberField from './components/NumberField.svelte';
  import TextField from './components/TextField.svelte';
  import DateField from './components/DateField.svelte';
  import Toggle from './components/Toggle.svelte';
  const filters = [
    "media",
    "images",
    "vine",
    "native_video",
    "periscope",
    "news",
    "links",
    "safe",
    "verified",
    "retweets",
    "nativeretweets"
  ]
  // $: {
  //   console.log({ $tweetURL, $settings })
  // }
  const submit = () => {
    window.open($tweetURL)
  };

  let showInvalidWarning = false
  settings.subscribe(x => {
    const datesSince = x["since"]
    const datesUntil = x["until"]
    showInvalidWarning = datesSince && datesUntil && datesSince > datesUntil
  })
</script>

<style global lang="scss">

  h1 {
    margin-block-start: 0;
    color: #ff3e00;
    text-transform: uppercase;
    font-size: 4em;
    font-weight: 100;
  }
  @media only screen and (max-width: 600px) {
    h1 {
      font-size: 1.5em;
    }
  }


  form, .grid3 {
    margin: 0 auto;
    display: grid;
    grid-template-columns: 1fr auto 1fr;
    grid-column-gap: 1rem;
    grid-row-gap: .5rem;
    align-items: center;
  }
  :root {
    --border-color: #444;
  }

  input[type='text'], input[type='number'], input[type='date'] {
    width: 100%
  }
  button, input {
    background: #fff;
    outline: none;
    /* border: .12em solid #444;
    box-shadow: 2px 2px 0 0 #444; */
    border: .12em solid var(--border-color);
    box-shadow: var(--border-color) 2px 2px 0 0;
    padding: .5em;
    transition: all .1s ease-in;
  }

  * {
    border-radius: 2px;
  }

  .details-content {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    max-width: 100%;
  }
  @media only screen and (max-width: 600px) {
    .details-content {
      grid-template-columns: 1fr 1fr;
    }
  }
  h2 {
    display: inline
  }
  form>#highlight, 
  form>.details-content, 
  form>button[type=submit], 
  form>h2,
  .span3,
  details {
    grid-column: 1/span 3;
  }
  footer * {
    white-space: pre-wrap;
  }
  footer, main {
    padding: 1rem;
    /* width: 100%; */
  }
  @media only screen and (min-width: 1000px) {
    footer, main {
      padding: 3rem;
    }
    #searchKeyword {
      --border-color: #5614B0;
      font-size: 200%;
    }
    button[type="submit"] {
      font-size: 200%;
    }
  }
  button[type="submit"] {
    --border-color: darkgreen;
    cursor: pointer;
    background: #d9a7c7;  /* fallback for old browsers */
    background: -webkit-linear-gradient(to right, #fffcdc, #d9a7c7);  /* Chrome 10-25, Safari 5.1-6 */
    background: linear-gradient(to right, #fffcdc, #d9a7c7); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
  }
</style>

<main>
  <h1>Better Twitter</h1>
  <form on:submit|preventDefault="{submit}">
    <TextField label="User from" fieldName="from">
    </TextField>
    <div></div>
    <Toggle>Tweets From People You Follow</Toggle>
    <div></div>
    <TextField label="User to" fieldName="to" />

    <details>
      <summary>
        <h2>Dates</h2>
      </summary>
      <div class="grid3">
        <DateField label="Since" fieldName="since"/>
        {#if showInvalidWarning}
        <div class="span3">⚠️ Warning: <pre>Since</pre>should come before<pre>Until</pre></div>
        {/if}
        <DateField label="Until" fieldName="until"/>
      </div>
    </details>
    <details>
      <summary>
        <h2>Filters</h2>
      </summary>
      <div class="details-content">
        {#each filters as filter}
          <FilterField fieldType={filter} />
        {/each}
      </div>
    </details>
    <details>
      <summary>
        <h2>Quality</h2>
      </summary>
      <div class="grid3">
      <NumberField fieldName="min_retweets" label="min_retweets" />
      <NumberField fieldName="min_faves" label="min_faves" />
      </div>
    </details>
    <TextField label="keyword" fieldName="searchKeyword" placeholder={'search...'}>
      <em>leaving blank is ok</em>
    </TextField> 


    <div id="highlight">
      <h2>Tips</h2>
      <ul>
        <li>
          Dont forget you can search "exact quotes", @usernames or #hashtags
        </li>
        <li>Minus Operator e.g. `-RT` or `beer -root`</li>
        <li>OR Operator e.g. `#Emmys OR #Emmys2015`</li>
      </ul>
    </div>

    <button type="submit">Open search results</button>
  </form>
  <footer>
    <pre>This app is definitely a work in progress. </pre>
    <pre>
      <a href="https://github.com/sw-yx/bettertwitter">Send ideas/Check out the todo/wishlist here.</a>
    </pre>
    Bouquets and brickbats to <a href="https://twitter.com/swyx">@swyx</a>
  </footer>
</main>
